/* Based on https://github.com/jaredlll08/MultiLoader-Template/ */

plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

// All jar files from this folder will be added automatically as runtime mod dependencies (inspired by AE2's build.gradle)
def extraModsDir = "extra-mods"

repositories {
    flatDir {
        name "extra-mods"
        dir file(extraModsDir)
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.7.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.7.1'
    testImplementation 'org.junit.platform:junit-platform-suite-api:1.14.1'
    testImplementation 'org.hamcrest:hamcrest:2.1'
    testImplementation "org.mockito:mockito-core:2.+"
    testRuntimeOnly 'org.junit.platform:junit-platform-suite-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // Locally sourced extra mods for runtime (i.e. testing)
    for (extraModJar in fileTree(dir: extraModsDir, include: '*.jar')) {
        def basename = extraModJar.name.substring(0, extraModJar.name.length() - ".jar".length())
        def versionSep = basename.lastIndexOf('-')
        assert versionSep != -1
        def artifactId = basename.substring(0, versionSep)
        def version = basename.substring(versionSep + 1)
        runtimeOnly "extra-mods:$artifactId:$version"
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

neoForge {
    version = "${neoforge_version}"

    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':loader-common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = [ at.absolutePath ]
    }

    validateAccessTransformers = true

    runs {
        client {
            client()
        }
        server {
            server()
        }
        gameTestServer {
            type = "gameTestServer"
        }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
            systemProperty 'neoforge.enabledGameTestNamespaces', "cyclopscore,${mod_id}"
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

// Disabled because signed jars are not being checked anyways
//tasks.register('signJar').configure {
//    dependsOn(tasks.jar)
//
//    onlyIf {
//        System.getenv().SIGN_KEYSTORE
//    }
//
//    keyStore = System.getenv().SIGN_KEYSTORE
//    alias = System.getenv().SIGN_ALIAS
//    storePass = System.getenv().SIGN_STOREPASS
//    keyPass = System.getenv().SIGN_KEYPASS
//    input = jar.archivePath
//    output = jar.archivePath
//}

// Measure coverage for game tests
jacocoTestReport {
    // Include unit and game test coverage
    dependsOn test, runGameTestServer
    executionData fileTree(project.buildDir).include("jacoco/*.exec")
}
jacoco.applyTo(runGameTestServer)
