# Project
mod_version=1.3.1
group=org.cyclops.iconexporter
java_version=21

# Common
minecraft_version=1.21.8
mod_name=IconExporter
mod_author=rubensworks (aka kroeser)
mod_id=iconexporter
license=MIT
github_url=https://github.com/CyclopsMC/IconExporter
issue_tracker_url=https://github.com/CyclopsMC/IconExporter/issues
display_url=https://www.curseforge.com/minecraft/mc-mods/iconexporter
description=Exports item and block icons to files.
fingerprint=bd0353b3e8a2810d60dd584e256e364bc3bedd44
neo_form_version=1.21.7-20250630.141722
parchment_version=2025.06.15
parchment_minecraft_version=1.21.5
curseforge_project_id=327048
modrinth_project_id=8KCmS7Bd

# Fabric
fabric_version=0.130.0+1.21.8
fabric_loader_version=0.16.14
# Dependencies
fabric_forgeconfigapiport_version=21.8.0

# NeoForge
neoforge_version=21.8.20
neoforge_loader_version_range=[4,)
neoforge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/neoforge_update/iconexporter.json

# Forge
forge_version=58.0.1
forge_loader_version_range=[2,)
forge_update_json_url=https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/iconexporter.json

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.caching=true

# Common dependencies
cyclopscore_version=1.25.5-793
