modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/CyclopsMC/IconExporter/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/iconexporter"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"

[[mods]]
modId="iconexporter"
version="${file.jarVersion}"
displayName="IconExporter"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/iconexporter.json"
description='''
Exports item and block icons to files.
'''
[[dependencies.iconexporter]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconexporter]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconexporter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,]"
    ordering="NONE"
    side="BOTH"
