modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/CyclopsMC/IconExporter/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/iconexporter"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"

[[mods]]
modId="iconexporter"
version="${file.jarVersion}"
displayName="IconExporter"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/iconexporter.json"
description='''
Exports item and block icons to files.
'''
[[dependencies.iconexporter]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.18.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconexporter]]
    modId="forge"
    mandatory=true
    versionRange="[47.0.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconexporter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,]"
    ordering="NONE"
    side="BOTH"
