modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/CyclopsMC/IconExporter/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/iconexporter"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"

[[mods]]
modId="iconexporter"
version="${file.jarVersion}"
displayName="IconExporter"
description='''
Exports item and block icons to files.
'''
[[dependencies.iconexporter]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.9.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconexporter]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconexporter]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,]"
    ordering="NONE"
    side="BOTH"
