modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/IconExporter/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/iconexporter"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"

[[mods]]
modId="iconexporter"
version="${file.jarVersion}"
displayName="IconExporter"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/iconexporter.json"
description='''
Exports item and block icons to files.
'''
[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"
[[dependencies.iconexporter]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconexporter]]
    modId="neoforge"
    type="required"
    versionRange="[21.0.43-beta,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.iconexporter]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,]"
    ordering="NONE"
    side="BOTH"
