modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="${issue_tracker_url}"
displayURL="${display_url}"
license="${license}"
logoFile="logo.png"
authors="${mod_author}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="${neoforge_update_json_url}"
description="${description}"
[[dependencies.${mod_id}]]
    modId="cyclopscore"
    type="required"
    versionRange="[${cyclopscore_version_semver},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version},]"
    ordering="NONE"
    side="BOTH"
