modLoader="javafml"
loaderVersion="${forge_loader_version_range}"
issueTrackerURL="${issue_tracker_url}"
displayURL="${display_url}"
license="${license}"
logoFile="logo.png"
authors="${mod_author}"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="${forge_update_json_url}"
description="${description}"
[[dependencies.${mod_id}]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[${cyclopscore_version_semver},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minecraft_version},]"
    ordering="NONE"
    side="BOTH"
